import AVFoundation
import Foundation

/// Plays the pre-rendered reminder audio clips (T-024) bundled under
/// `Resources/audio/`. `AVAudioPlayer` playback is instant — no speech-service
/// spin-up — and the clips are rendered with a neural voice for a more natural
/// sound. Clips are generated by `scripts/generate-reminder-audio.sh`.
@MainActor
final class ReminderAudioPlayer {
    /// Retains players while they play (an `AVAudioPlayer` stops if deallocated).
    private var active: [AVAudioPlayer] = []

    /// Plays the clip named `key` (an `m4a` in `Resources/audio/`). Returns
    /// `false` if the clip is missing or can't be loaded, so the caller can
    /// fall back to live TTS.
    func play(key: String, volume: Float) -> Bool {
        guard let url = Self.url(forKey: key),
              let player = try? AVAudioPlayer(contentsOf: url)
        else { return false }
        active.removeAll { !$0.isPlaying }
        player.volume = volume
        player.prepareToPlay()
        player.play()
        active.append(player)
        return true
    }

    private static func url(forKey key: String) -> URL? {
        Bundle.module.url(forResource: key, withExtension: "m4a", subdirectory: "audio")
            ?? Bundle.module.url(forResource: key, withExtension: "m4a")
    }
}
