import AVFoundation
import Foundation

/// Plays the pre-rendered reminder audio clips (T-024) bundled under
/// `Resources/audio/`. `AVAudioPlayer` playback is instant — no speech-service
/// spin-up — and the clips are rendered with a neural voice for a more natural
/// sound. Clips are generated by `scripts/generate-reminder-audio.sh`.
@MainActor
final class ReminderAudioPlayer {
    /// Retains players while they play (an `AVAudioPlayer` stops if deallocated).
    private var active: [AVAudioPlayer] = []

    /// Plays the clip named `key` (an `m4a` in `Resources/audio/`). Returns
    /// `false` if the clip is missing or can't be loaded, so the caller can
    /// fall back to live TTS.
    func play(key: String, volume: Float) -> Bool {
        guard let url = Self.url(forKey: key),
              let player = try? AVAudioPlayer(contentsOf: url)
        else { return false }
        active.removeAll { !$0.isPlaying }
        player.volume = volume
        player.prepareToPlay()
        player.play()
        active.append(player)
        return true
    }

    private static func url(forKey key: String) -> URL? {
        Bundle.module.url(forResource: key, withExtension: "m4a", subdirectory: "audio")
            ?? Bundle.module.url(forResource: key, withExtension: "m4a")
    }

    /// Any bundled reminder clip, used purely to prime the audio stack (T-045).
    static func warmUpClipURL() -> URL? {
        Bundle.module.urls(forResourcesWithExtension: "m4a", subdirectory: "audio")?.first
            ?? Bundle.module.urls(forResourcesWithExtension: "m4a", subdirectory: nil)?.first
    }

    /// Primes the process's audio-output stack ahead of the first reminder
    /// (T-045). The first `AVAudioPlayer` playback has to acquire the audio
    /// hardware (coreaudiod), which can lag badly on a cold start — the same
    /// spin-up that otherwise stalls the first spoken reminder. Doing it once
    /// at launch, **on a background task at zero volume**, moves that cost off
    /// the main thread (so the UI never beach-balls) and gets it out of the way
    /// before any reminder fires. Once the process audio stack is engaged it
    /// stays warm, so later real plays are instant. No clip bundled → no-op.
    ///
    /// The player is created and used entirely inside the detached task (never
    /// crossing an actor boundary), so it needs no `Sendable` gymnastics; it's
    /// released when the task ends, having already warmed the shared stack.
    static func primeAudioStack() {
        guard let url = warmUpClipURL() else { return }
        Task.detached(priority: .utility) {
            guard let player = try? AVAudioPlayer(contentsOf: url) else { return }
            player.volume = 0
            player.prepareToPlay()
            player.play()
            try? await Task.sleep(for: .milliseconds(250))
            player.stop()
        }
    }
}
